### ISSUE TITLE
Can you publish a wheel?

### ISSUE THREAD

**Issue by matthewdeanmartin** [amzn/ion-python#192]
Hello, I see that there is a sdist on pypi, but not a wheel. Wheels are useful (among other things) for if your team or organization mandates using `PIP_ONLY_BINARY=:all:` so that arbitrary code can't run in setup.py -- it is a supply chain risk mitigation.

These are the [steps to create a wheel](https://realpython.com/python-wheels/#building-a-pure-python-wheel), essentially you add bdist_wheel, e.g. `python setup.py build sdist bdist_wheel` and upload both with twine.  Poetry can also create wheels with less ceremony.

I'd make a PR, but pypi deployment processes are not usually included in the source code.

Thanks

**Comment by cheqianh** [comment]
Hi matthewdeanmartin@, thanks for the recommendation. We're planning on adding a wheel distribution.

A little background information about our two latest releases `v0.8.0` and `v0.9.0`. `v0.8.0` is implemented in pure python and `v0.9.0` did only one change which is adding native C code (C extension). Since v0.9.0 includes a C extension and requires platform specified binaries, its wheels are also platform/python version specified where we have to setup pipelines/infrastructures to release them.

**Comment by cheqianh** [comment]
Wheel distribution is available in [PYPI](https://pypi.org/project/amazon.ion/#files) since 0.9.2
