### ISSUE TITLE
Mapping of tuple type

### ISSUE THREAD

**Issue by robcalhounjr** [amzn/ion-python#96]
In https://github.com/amzn/ion-python/commit/7651c7a4fe7d736dc439e45edd6ce28f5da429e1 I see that a python `tuple` is mapped to `IonType.LIST`. My expectation is that it would be to `IonType.SEXP`. At least that's what I have in my workspace and it works as I would expect.

Isn't mapping it List effectively losing data?

**Comment by tgregg** [comment]
A python tuple is just an immutable sequence. It does not have s-expression semantics. Most python applications that expect a sequence type would not behave differently based on whether the type is a list or tuple, and ion-python follows that practice.

To write an Ion s-expression, wrap your tuple using `IonPyList.from_value(IonType.SEXP, ())`.

Data is not lost because when an s-expression is read by `simpleion.load`, it will produce an `IonPyList` with the type `IonType.SEXP`. When this is written with `simpleion.dump`, it will produce an s-expression.

**Comment by dlurton** [comment]
Looks like there are workarounds which allow `tuple`s to be written as `IonType.SEXP` so I'm closing this for now.  Please re-open if there are additional questions.  Thanks.

**Comment by almann** [comment]
Given the use of `tuple` types in Python as an immutable sequence (in cases that `list` would not be appropriate such as module level properties), I am not inclined to make a *default* mapping for `tuple` to `sexp` (I can think of many use cases that this would be surprising behavior).

That said, I do think having a way to customize the mapping table as a public API is appropriate, as there are many potential use cases there.  The Python [json](https://docs.python.org/3/library/json.html) module supports customizing how [decoding and encoding work](https://docs.python.org/3/library/json.html#encoders-and-decoders).  I am not saying we expose exactly this functionality, but it may serve as an example.

**Comment by tgregg** [comment]
`tuple_as_sexp` option added in #101.
